### ISSUE TITLE
Folia Error Scheduler

### ISSUE THREAD

**Issue by Euphillya** [WiIIiam278/HuskChat#252] opened 2024-07-11 20:12 UTC
https://github.com/WiIIiam278/HuskChat/blob/2999358a0136779451f18218afa58c8d1aa21a6f/bukkit/src/main/java/net/william278/huskchat/event/BukkitEventProvider.java#L37

https://github.com/WiIIiam278/HuskChat/blob/2999358a0136779451f18218afa58c8d1aa21a6f/bukkit/src/main/java/net/william278/huskchat/event/BukkitEventProvider.java#L50

Schedulers are not functional on Folia, because it uses those from bukkit.

**Comment by WiIIiam278** [comment] 2024-07-11 21:36
Duplicate of #226

**Closed by WiIIiam278** 2024-07-11 21:36 UTC

**Comment by Euphillya** [comment] 2024-07-12 04:35
Duplicate but not fixed
