### ISSUE TITLE
Social and Local Spy not exempting Authors and recipients 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskChat#23] opened 2022-03-20 23:11 UTC
The local spy and Social Spy commands do not appear to have any mechnism to exempt players who send the PMs or receive them, when they possess the permission, from receiving a Spy message themselves.

This may cause confusion and may cause unnecessary spam inside chat...

**Comment by Iotados** [comment] 2022-03-20 23:16
I'm going off third party testing for this... Will try to confirm this tomorrow however the results I have been shown seem consistent with others reports

**Comment by WiIIiam278** [comment] 2022-04-11 15:01
Duplicate of https://github.com/WiIIiam278/HuskChat/issues/29

**Closed by WiIIiam278** 2022-04-11 15:01 UTC
Labels: priority: medium, type: bug
