### ISSUE TITLE
Change the chat color 

### ISSUE THREAD

**Issue by ICookBacon123** [WiIIiam278/HuskChat#115] opened 2023-04-30 23:54 UTC
Be able to change the chat color (Or make it possible that u can turn off HuskChat is overrulling the chat formatter). 
We have a chat color plugin that doesn't work anymore, and we dont want the chat color to be white.

**Comment by WiIIiam278** [comment] 2023-05-01 01:10
Duplicate of #98

**Closed by WiIIiam278** 2023-05-01 01:10 UTC
